// This file is automatically generated.
// Please do not change this file!
interface CssExports {
	aside: string
	asideMenu: string
	asidePreview: string
	asidePreviewWrapper: string
	loader: string
	post: string
	postDescription: string
	postImage: string
	postTitle: string
	postWrapper: string
}
export const cssExports: CssExports
export default cssExports
